version: "3"
services:
  database:
    image: mongo:latest
    container_name: sado-database
    ports:
      - 27017:27017
    volumes:
      - ./.bin/data/mongodb:/data/db

  cache:
    image: redis
    container_name: sado-cache
    ports:
      - 6379:6379
    volumes:
      - ./.bin/data/redis:/data

  # api:
  #   image: sadoprotocol/api:0.0.0
  #   container_name: sado-api
  #   depends_on:
  #     - database
  #     - cache
  #   ports:
  #     - 3030:3030
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGODB_URI=mongodb://database:27017
  #     - REDIS_HOST=cache
