name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Clean Existing
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6 # v0.1.10
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          script: |
            cd ~/sado-api
            rm -rf ./src ./dist

      - name: Deploy Updates
        uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff # v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_SSH_HOST }}
          REMOTE_USER: ${{ secrets.EC2_SSH_USER }}
          TARGET: "/home/ubuntu/sado-api"
          EXCLUDE: "/.github/,/.vscode/,/.git/"

      - name: Build & Reload
        uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6 # v0.1.10
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          script: |
            PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.16.0/bin
            cd ~/sado-api
            npm i
            npm run build
            pm2 reload api

      - name: Notify
        id: slack
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "title": "Sado API New Release: ${{ github.event.release.name }}",
              "content": "Release Version: ${{ github.event.release.name }}\nRelease Notes: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}"
            }
